### ISSUE TITLE
Playback stops immediately (always)

### ISSUE THREAD

**Issue by STiAT** [lukedirtwalker/cutespotify#14]
On a new installation (latest version), even being on a stable connection (WLAN), playback immediately stops. I'm using streaming - not locally buffered files.

I did the following:
- resetted the complete device
- rebooted, installed the system updates
- installed warehouse
- installed cutespotify
- ran it + logged in
- went to "Top"
- played a song

=> The player appeared for a very short moment, but exited almost immediately again. This takes sometimes a bit longer, sometimes a bit shorter (between 0.5-2s I'd say) :).

I've run harbour-cutespotify --debug, but for me it does not make any sense or rather .. does not give any information.. maybe you can make more sense out of it.
http://pastebin.com/TxKtH2xA

If you need any further information, let me know, I'll help debugging, tracking and fixing/testing if you give me a hint where to look - source code whise.

**Comment by lukedirtwalker** [comment]
Is it the same for older version? It should be fixed in e4f3e524 and in the 1.5.2-2 release on OpenRepos.

**Comment by STiAT** [comment]
Yes, it's the same for all versions. I didn't use spotify in a while now, so it could be caused by the last system update either.

Question: I don't get a 1.5.2-2 release shown on openrepos... only 1.5.2-1 (which is the one not working).

**Comment by lukedirtwalker** [comment]
I pulled it as some user reported that system sounds no longer work. 
You can do:
pkcon install qt5-qtmultimedia-plugin-audio-pulseaudio
and then it will work however it might be that you face the same issues, but honestly I don't believe that this issue was related.

**Comment by STiAT** [comment]
Seems not to be related. Anything I can do to further track this and / or
help debugging?

**Comment by lukedirtwalker** [comment]
You can try if to put a debug statement on this line:
https://github.com/lukedirtwalker/libQtSpotify/blob/thread_safe/qspotifyaudiothreadworker.cpp#L117
and see if that is printed. But that would mean that you could solve it with installing the pulseaudio plugin, other than that I don't have any ideas at the moment.
