### ISSUE TITLE
Add to playlist-dialog does not show playlist folders

### ISSUE THREAD

**Issue by hetas** [lukedirtwalker/cutespotify#21]
It's not possible to add a song to playlist in a playlist folder because Add to playlist-dialog does not list playlist folders. Only playlist outside folders are shown.

Cutespot version 1.5.4-1.

**Comment by lukedirtwalker** [comment]
ACK

Note to self: Use playlistsFlat in PlaylistSelectionDialog:updatePlaylists() to fix this
