### ISSUE TITLE
Show artist view broken

### ISSUE THREAD

**Issue by ghost** [lukedirtwalker/cutespotify#29]
Steps to reproduce:
1. Select search
2. Search for an artist/song/whatever
3. Select an artist from the search results
4. Only a cover image is shown, no tracks or other infor, so basically a blank page (see image)
![20150627222646](https://cloud.githubusercontent.com/assets/10125900/8401882/096b21f4-1e3e-11e5-8cfa-bdd2060d24ff.jpg)

Using the latest SFOS (1.1.6.) and OpenRepos version of CuteSpot.

**Comment by lukedirtwalker** [comment]
@raketti Thanks for reporting, can you confirm that this is still the case? I think it was a temporary problem with spotify's service, which seems to be resolved now.

**Comment by ghost** [comment]
Actually now it seems to work as it should. "Good" to hear it was a problem in the service and not the app. So closing this one.
