### ISSUE TITLE
When pushing "next song", Cutespot jumps ahead more than ten songs

### ISSUE THREAD

**Issue by jpi68** [lukedirtwalker/cutespotify#34]
This is happening in Jolla and the latest Sailfish update. Before update the OS it works ok. Same thing happens in the care when pushing "next" in the steering wheel buttons.

**Comment by jpi68** [comment]
Sorry, this was a problem in Cutespot version 1.5.7-1.  When I installed 1.5.7.-0 from Jolla Store in works ok again.  Thanks for the great app.

**Comment by lukedirtwalker** [comment]
Closing, since the Openrepos version is broken in newer OS versions.
