### ISSUE TITLE
Bluetooth controls don't work with Sailfish 2.0.4.14

### ISSUE THREAD

**Issue by vige** [lukedirtwalker/cutespotify#36]
The bluetooth controls used to work, but with Sailfish OS version 2.0.4.14 they don't work anymore.

**Comment by nagua** [comment]
I had the same problem. The solution is to install the app from warehouse and not from harbor. The app got updated to the harbor version somehow. Then I needed to update it again from warehouse to be able to use bluetooth controls.

**Comment by lukedirtwalker** [comment]
@vige  Can we close this one?

**Comment by vige** [comment]
sure
